spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.155.215.158:3306/passjava_cms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: dusk
    password: Dusk@1009

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848

  application:
    name: passjava-content

  mybatis-plus:
    mapper-locations: classpath:/mapper/**/*.xml
    global-config:
      db-config:
        id-type: auto

server:
  port: 9001
